# Generated by Django 5.1.5 on 2025-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='watermark',
            field=models.ImageField(blank=True, null=True, upload_to='watermarks/'),
        ),
    ]
