# Generated by Django 5.1.5 on 2025-01-23 16:54

import salary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_salaryslip_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[salary.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='watermark',
            field=models.ImageField(blank=True, null=True, upload_to='watermarks/', validators=[salary.models.validate_file_extension]),
        ),
    ]
