# Generated by Django 5.1.5 on 2025-01-24 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
