# Generated by Django 5.1.5 on 2025-01-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_salaryslip_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='company_info',
            new_name='company_name_info',
        ),
    ]
