# Generated by Django 5.1.5 on 2025-01-24 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_rename_company_info_salaryslip_company_name_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
