# Generated by Django 5.1.5 on 2025-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_rename_created_at_salaryslip_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='slip_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
