# Generated by Django 5.1.5 on 2025-01-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_salaryslip_slip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
