# Generated by Django 5.1.5 on 2025-01-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_salaryslip_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='payslip_number',
            new_name='payslip_month',
        ),
    ]
