# Generated by Django 5.1.5 on 2025-01-25 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_rename_payslip_number_salaryslip_payslip_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryslip',
            name='id',
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='slip_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to=settings.AUTH_USER_MODEL),
        ),
    ]
